# Render.com configuration file
services:
  - type: web
    name: school-management-system
    env: php
    buildCommand: composer install
    startCommand: |
      echo "LoadModule rewrite_module /usr/lib/apache2/modules/mod_rewrite.so" > apache_config
      vendor/bin/heroku-php-apache2 -C apache_config .
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
    runtime: php
    phpVersion: 8.0
    healthCheckPath: /
    autoDeploy: true